import type { AppState, ApplicationSettings, CommandRecipe, HostProfile, ScriptRecipe } from "./types";

const legacyDemoHostIds = new Set([
  "host-sg-prod",
  "host-hk-gateway",
  "host-tokyo-test",
]);

export const builtInScripts: ScriptRecipe[] = [
  {
    id: "script-safevps",
    title: "SafeVPS 安全加固",
    description: "服务器安全配置与加固脚本",
    category: "自建工具",
    sourceUrl: "https://github.com/sanrokamlan-prog/safevps",
    command: "wget -O setup_server_security.sh https://raw.githubusercontent.com/sanrokamlan-prog/safevps/main/setup_server_security.sh && sudo bash setup_server_security.sh",
    risk: "high",
  },
  {
    id: "script-nginx-easy-deploy",
    title: "Nginx Easy Deploy",
    description: "Nginx 站点与证书部署工具",
    category: "自建工具",
    sourceUrl: "https://github.com/sanrokamlan-prog/nginx-easy-deploy",
    command: "VERSION=v0.5.0\nBASE=\"https://github.com/sanrokamlan-prog/nginx-easy-deploy/releases/download/${VERSION}\"\ncurl -fLO \"${BASE}/nginx-easy-deploy.sh\"\ncurl -fLO \"${BASE}/SHA256SUMS\"\nsha256sum -c SHA256SUMS\nsudo bash nginx-easy-deploy.sh",
    risk: "high",
  },
  {
    id: "script-vps-health-check",
    title: "VPS Health Check",
    description: "服务器健康状态巡检",
    category: "自建工具",
    sourceUrl: "https://github.com/sanrokamlan-prog/vps-health-check",
    command: "curl -fsSL https://github.com/sanrokamlan-prog/vps-health-check/releases/download/v1.3.0/vps-health-check.sh -o /tmp/vps-health-check.sh && sudo bash /tmp/vps-health-check.sh",
    risk: "low",
  },
  {
    id: "script-region-check",
    title: "流媒体解锁测试",
    description: "检测常见流媒体服务的区域可用性",
    category: "网络检测",
    sourceUrl: "https://github.com/1-stream/RegionRestrictionCheck",
    command: "bash <(curl -L -s https://raw.githubusercontent.com/1-stream/RegionRestrictionCheck/main/check.sh)",
    risk: "medium",
  },
  {
    id: "script-check-place",
    title: "IP 风险与线路检测",
    description: "使用 Check.Place 检测 IP 与线路",
    category: "网络检测",
    sourceUrl: "https://Check.Place",
    command: "bash <(curl -Ls https://Check.Place) -I",
    risk: "medium",
  },
  {
    id: "script-neko-tools",
    title: "NekoCloud 综合工具箱",
    description: "通过明文 HTTP 下载的综合 VPS 工具箱",
    category: "综合工具",
    sourceUrl: "http://sh.nekoneko.cloud/tools.sh",
    command: "wget http://sh.nekoneko.cloud/tools.sh -O tools.sh && bash tools.sh",
    risk: "high",
  },
  {
    id: "script-node-quality",
    title: "NodeQuality 节点质量测试",
    description: "综合检测节点性能、网络与 IP 质量",
    category: "网络检测",
    sourceUrl: "https://run.NodeQuality.com",
    command: "bash <(curl -sL https://run.NodeQuality.com)",
    risk: "medium",
  },
  {
    id: "script-bbr-tune",
    title: "BBR 网络优化",
    description: "修改内核网络参数并启用 BBR 调优",
    category: "系统优化",
    sourceUrl: "https://github.com/chnnic/BBR-tune",
    command: "bash <(curl -fsSL https://raw.githubusercontent.com/chnnic/BBR-tune/refs/heads/main/bbr-tune.sh)",
    risk: "high",
  },
  {
    id: "script-dd-system",
    title: "DD 重装系统",
    description: "擦除磁盘并重新安装操作系统",
    category: "系统重装",
    sourceUrl: "",
    risk: "destructive",
    parameters: ["目标系统", "登录密码", "SSH 端口"],
  },
];

export const builtInCommands: CommandRecipe[] = [
  {
    id: "command-os-info",
    title: "查看系统与内核信息",
    description: "显示发行版、内核、架构和主机名，适合先确认当前机器环境。",
    category: "系统信息",
    command: "printf '%s\\n' '--- OS ---'; cat /etc/os-release 2>/dev/null; printf '%s\\n' '--- Kernel ---'; uname -a; printf '%s\\n' '--- Host ---'; hostnamectl 2>/dev/null || hostname",
    usage: "连接服务器后运行，不会修改系统。",
    keywords: ["系统", "版本", "发行版", "linux", "内核", "架构", "主机名", "os", "uname", "hostname"],
    risk: "low",
  },
  {
    id: "command-uptime-load",
    title: "查看运行时间与负载",
    description: "检查服务器已运行多久，以及最近 1、5、15 分钟的平均负载。",
    category: "系统信息",
    command: "uptime; printf '\\n'; cat /proc/loadavg",
    usage: "负载持续高于 CPU 核心数时，再结合进程和内存继续排查。",
    keywords: ["运行时间", "负载", "卡顿", "很慢", "压力", "uptime", "load", "loadavg"],
    risk: "low",
  },
  {
    id: "command-disk-usage",
    title: "查看磁盘空间",
    description: "以易读格式显示文件系统类型、容量、已用空间和挂载点。",
    category: "磁盘与文件",
    command: "df -hT",
    usage: "重点留意使用率接近 100% 的根分区和数据盘。",
    keywords: ["磁盘", "硬盘", "空间", "容量", "满了", "分区", "挂载", "df"],
    risk: "low",
  },
  {
    id: "command-largest-directories",
    title: "查找根目录占用最大的目录",
    description: "统计当前文件系统根目录下各一级目录的大小，并列出最大的 20 项。",
    category: "磁盘与文件",
    command: "sudo du -xhd1 / 2>/dev/null | sort -h | tail -n 20",
    usage: "扫描大磁盘会产生较多磁盘读取；结果只统计当前文件系统。",
    keywords: ["大文件", "大目录", "占用", "磁盘清理", "空间去哪了", "du", "目录大小"],
    risk: "medium",
  },
  {
    id: "command-memory",
    title: "查看内存与交换分区",
    description: "显示内存、缓存和 Swap 使用情况。",
    category: "系统信息",
    command: "free -h; printf '\\n'; swapon --show 2>/dev/null || true",
    usage: "先看 available，而不是只看 free；缓存通常可由系统回收。",
    keywords: ["内存", "缓存", "交换", "swap", "oom", "爆内存", "free"],
    risk: "low",
  },
  {
    id: "command-failed-units",
    title: "查看失败的 systemd 服务",
    description: "列出当前启动失败或运行异常的 systemd 单元。",
    category: "服务排障",
    command: "systemctl --failed --no-pager",
    usage: "如果某项失败，可继续用“查看服务日志”并填入对应服务名。",
    keywords: ["服务失败", "启动失败", "systemd", "异常服务", "failed", "unit"],
    risk: "low",
  },
  {
    id: "command-service-logs",
    title: "查看指定服务最近日志",
    description: "读取指定 systemd 服务最近 200 行日志，并显示完整时间。",
    category: "服务排障",
    command: "journalctl -u {{SERVICE}} -n 200 --no-pager -o short-iso",
    usage: "将 SERVICE 替换为服务单元名，例如 nginx、docker 或 ssh。",
    keywords: ["日志", "报错", "服务日志", "journal", "journalctl", "systemctl", "nginx日志", "docker日志"],
    risk: "low",
    parameters: [
      {
        name: "SERVICE",
        label: "服务名称",
        placeholder: "例如 nginx 或 docker",
        required: true,
      },
    ],
  },
  {
    id: "command-listening-ports",
    title: "查看监听端口与进程",
    description: "列出 TCP/UDP 监听端口及对应进程。",
    category: "网络诊断",
    command: "sudo ss -lntup",
    usage: "可用来确认 Web、SSH 或数据库服务是否正在监听预期端口。",
    keywords: ["端口", "监听", "进程", "端口占用", "服务没开", "ss", "netstat", "tcp", "udp"],
    risk: "low",
  },
  {
    id: "command-route",
    title: "查看本机 IP 与路由",
    description: "显示网卡地址、默认网关和完整路由表。",
    category: "网络诊断",
    command: "ip -brief address; printf '\\n--- routes ---\\n'; ip route",
    usage: "用于确认内网地址、默认出口和静态路由。",
    keywords: ["ip", "内网ip", "网卡", "网关", "默认路由", "路由表", "ip route", "网络配置"],
    risk: "low",
  },
  {
    id: "command-dns",
    title: "查看 DNS 配置与解析",
    description: "显示系统 DNS 配置，并解析指定域名的地址。",
    category: "网络诊断",
    command: "cat /etc/resolv.conf; printf '\\n--- lookup ---\\n'; getent ahosts {{DOMAIN}} | head -n 10",
    usage: "填写需要排查的域名，例如 example.com。",
    keywords: ["dns", "域名", "解析", "打不开", "resolv", "nameserver", "getent"],
    risk: "low",
    parameters: [
      {
        name: "DOMAIN",
        label: "域名",
        placeholder: "example.com",
        defaultValue: "example.com",
        required: true,
      },
    ],
  },
  {
    id: "command-public-ip",
    title: "查看服务器公网 IP",
    description: "通过 HTTPS 查询当前服务器对外访问时使用的公网 IP。",
    category: "网络诊断",
    command: "curl -fsS --max-time 10 https://api.ipify.org && printf '\\n'",
    usage: "命令会向 api.ipify.org 发起一次 HTTPS 请求。",
    keywords: ["公网ip", "出口ip", "外网ip", "真实ip", "ip地址", "ipify"],
    risk: "low",
  },
  {
    id: "command-docker-ps",
    title: "查看 Docker 容器状态",
    description: "列出全部容器及其镜像、状态、端口和名称。",
    category: "容器",
    command: "docker ps -a --format 'table {{.Names}}\\t{{.Image}}\\t{{.Status}}\\t{{.Ports}}'",
    usage: "如果当前用户无 Docker 权限，可在命令前加 sudo。",
    keywords: ["docker", "容器", "容器状态", "镜像", "docker ps", "compose"],
    risk: "low",
  },
  {
    id: "command-docker-stats",
    title: "查看 Docker 资源占用",
    description: "抓取一次容器 CPU、内存、网络和磁盘 I/O 快照。",
    category: "容器",
    command: "docker stats --no-stream",
    usage: "该命令只读取一次快照，不会持续占用终端。",
    keywords: ["docker", "容器", "cpu", "内存", "资源", "性能", "docker stats"],
    risk: "low",
  },
  {
    id: "command-docker-logs",
    title: "查看指定容器日志",
    description: "显示指定容器最近 200 行日志及时间戳。",
    category: "容器",
    command: "docker logs --timestamps --tail 200 {{CONTAINER}}",
    usage: "填写 docker ps 中显示的容器名称或 ID。",
    keywords: ["docker日志", "容器日志", "容器报错", "docker logs", "排障"],
    risk: "low",
    parameters: [
      {
        name: "CONTAINER",
        label: "容器名称或 ID",
        placeholder: "例如 nginx",
        required: true,
      },
    ],
  },
  {
    id: "command-nginx-check-reload",
    title: "检查并重载 Nginx",
    description: "配置检查通过后才平滑重载 Nginx，现有连接不会被直接中断。",
    category: "Web 服务",
    command: "sudo nginx -t && sudo systemctl reload nginx",
    usage: "会更改 Nginx 运行状态；配置检查失败时不会执行重载。",
    keywords: ["nginx", "配置检查", "重载", "reload", "网站配置", "反向代理"],
    risk: "medium",
  },
  {
    id: "command-ufw-status",
    title: "查看 UFW 防火墙规则",
    description: "显示 UFW 是否启用以及带编号的规则列表。",
    category: "安全检查",
    command: "sudo ufw status numbered",
    usage: "只读取当前规则，不会开放或关闭端口。",
    keywords: ["防火墙", "ufw", "端口规则", "放行", "拦截", "安全组"],
    risk: "low",
  },
  {
    id: "command-fail2ban-status",
    title: "查看 Fail2ban 封禁状态",
    description: "显示 Fail2ban 服务状态和当前启用的 jail。",
    category: "安全检查",
    command: "sudo fail2ban-client status",
    usage: "要查看某个 jail 的详细封禁列表，可继续运行 fail2ban-client status JAIL。",
    keywords: ["fail2ban", "封禁", "暴力破解", "ssh攻击", "jail", "安全"],
    risk: "low",
  },
  {
    id: "action-install-public-key",
    title: "把当前 SSH 公钥加入服务器",
    description: "把本机已生成的公钥安全追加到当前服务器的 authorized_keys。",
    category: "SSH 密钥",
    usage: "先在密钥管理器生成或选择公钥；执行前会再次显示目标主机并确认。",
    keywords: ["ssh密钥", "公钥", "免密登录", "authorized_keys", "加密登录", "添加key", "上传公钥"],
    risk: "medium",
    action: "install-public-key",
  },
  {
    id: "action-trace-route",
    title: "路由追踪",
    description: "探测到目标地址经过的网络节点和每一跳延迟。",
    category: "网络诊断",
    usage: "填写域名或 IP；界面会选择系统可用的 tracepath、traceroute 或 ping 工具。",
    keywords: ["路由追踪", "线路", "经过哪里", "跳数", "延迟", "丢包", "traceroute", "tracepath", "mtr"],
    risk: "low",
    action: "trace-route",
    parameters: [
      {
        name: "TARGET",
        label: "目标域名或 IP",
        placeholder: "例如 1.1.1.1",
        defaultValue: "1.1.1.1",
        required: true,
      },
    ],
  },
  {
    id: "action-speed-test",
    title: "网络速度测试",
    description: "测试服务器的下载速度、延迟和基础网络质量。",
    category: "网络诊断",
    usage: "测速会消耗服务器流量和带宽；界面会在执行前显示测试方式并确认。",
    keywords: ["测速", "速度测试", "下载速度", "带宽", "网速", "延迟", "speedtest", "iperf"],
    risk: "medium",
    action: "speed-test",
  },
  {
    id: "action-udp-speed-test",
    title: "本机与 VPS UDP 测速",
    description: "使用本机 iperf3 测量到自建 VPS 的 UDP 吞吐、抖动与丢包。",
    category: "网络诊断",
    usage: "VPS 需先启动 iperf3 服务端；支持本机到 VPS 和反向 VPS 到本机。",
    keywords: ["udp测速", "iperf3", "本机到vps", "vps到本机", "丢包", "抖动", "带宽"],
    risk: "medium",
    action: "udp-speed-test",
  },
  {
    id: "command-iperf3-server",
    title: "临时启动 iperf3 测速服务",
    description: "在当前 VPS 前台启动 iperf3 服务端，关闭终端或按 Ctrl+C 即停止。",
    category: "网络诊断",
    command: "iperf3 -s -p {{PORT}}",
    usage: "需要先安装 iperf3，并在防火墙与云安全组中临时放行同一 TCP/UDP 端口。",
    keywords: ["启动测速服务", "iperf服务端", "udp服务端", "自建测速", "iperf3 server"],
    risk: "medium",
    parameters: [{ name: "PORT", label: "监听端口", defaultValue: "5201", required: true }],
  },
];

export const initialState: AppState = {
  hosts: [],
  deletedHosts: [],
  scripts: builtInScripts,
  commands: builtInCommands,
  sshKeys: [],
  commandHistory: [],
  connectionHistory: [],
  pathHistory: {},
  sync: {
    enabled: false,
    provider: "webdav",
    endpoint: "",
    remotePath: "/vpshell",
    username: "",
    totpEnabled: false,
    syncSecrets: false,
  },
  wallpaper: {
    source: "none",
    value: "",
    opacity: 0.2,
  },
  terminalAppearance: {
    fontFamily: "Cascadia Code",
    fontSize: 13,
    lineHeight: 1.25,
  },
  settings: {
    externalEditorPath: "",
    autoUploadEditedFiles: false,
  },
  onboardingCompleted: false,
};

/** Remove only the three profiles shipped as legacy demos and their exact references. */
export function migratePersistedAppState(value: AppState): AppState {
  const sourceHosts = Array.isArray(value.hosts) ? value.hosts : [];
  const hosts = sourceHosts
    .filter((host) => !legacyDemoHostIds.has(host.id))
    .map((host) => {
      const directHost = { ...host } as HostProfile & {
        jumpMode?: unknown;
        jumpHostId?: unknown;
        proxyJump?: unknown;
      };
      delete directHost.jumpMode;
      delete directHost.jumpHostId;
      delete directHost.proxyJump;
      return directHost;
    });
  const pathHistory = Object.fromEntries(
    Object.entries(value.pathHistory ?? {}).filter(([hostId]) => !legacyDemoHostIds.has(hostId)),
  );
  const settings = {
    ...initialState.settings,
    ...(value.settings ?? {}),
  } as ApplicationSettings & { defaultJumpHostId?: unknown };
  delete settings.defaultJumpHostId;

  return {
    ...initialState,
    ...value,
    hosts,
    deletedHosts: value.deletedHosts ?? [],
    commandHistory: (value.commandHistory ?? []).filter((item) => !legacyDemoHostIds.has(item.hostId)),
    connectionHistory: (value.connectionHistory ?? []).filter((item) => !legacyDemoHostIds.has(item.hostId)),
    pathHistory,
    settings,
    onboardingCompleted: value.onboardingCompleted ?? false,
  };
}
